spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:noticianews

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
secret:
  ${secret}